const CONSTANTS = {
  STATUS_CHECK_TIMEOUT: 10000,
  STATUS_FAIL_TIMEOUT: 180000,
  LINEITEM_TYPES: {
    SPONSORSHIP: "SPONSORSHIP",
    STANDARD: "STANDARD",
    NETWORK: "NETWORK",
    BULK: "BULK",
    PRICE_PRIORITY: "PRICE_PRIORITY",
    HOUSE: "HOUSE",
    LEGACY_DFP: "LEGACY_DFP",
    CLICK_TRACKING: "CLICK_TRACKING",
    ADSENSE: "ADSENSE",
    AD_EXCHANGE: "AD_EXCHANGE",
    BUMPER: "BUMPER",
    ADMOB: "ADMOB",
    PREFERED_DEAL: "PREFERED_DEAL",
    UNKNOWN: "UNKNOWN",
  },
};

export default CONSTANTS;
